import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const initialRestaurants = [
  { id: 1, name: 'The Pepper House', type: 'Restaurant', city: 'Noida', status: 'Active', code: 'RV-R0001', mobile: '+91 98765 43210', address: 'NX One, Sector 14', state: 'Uttar Pradesh', pin: '201301' },
  { id: 2, name: 'Pepper Express', type: 'Cloud Kitchen', city: 'Gurugram', status: 'Inactive', code: 'RV-R0002', mobile: '+91 98765 43211', address: 'DLF Phase 3', state: 'Haryana', pin: '122002' }
];

function Mark() { return <div className="mark" aria-label="RestroVico"><span>R</span><i>V</i></div> }
function Icon({name}) { const p={grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',store:'M4 10h16v10H4zM3 10l2-6h14l2 6M8 20v-5h8v5',user:'M20 21a8 8 0 0 0-16 0M12 13a5 5 0 1 0 0-10 5 5 0 0 0 0 10',plus:'M12 5v14M5 12h14',arrow:'m9 18 6-6-6-6',check:'m5 12 4 4L19 6',logout:'M10 17l5-5-5-5M15 12H3M21 3v18'}[name]||''; return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={p}/></svg> }

function Field({label, children, hint}) { return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label> }
function Button({children, onClick, kind='primary', type='button', disabled}) { return <button type={type} className={'button '+kind} onClick={onClick} disabled={disabled}>{children}</button> }

function Auth({setMode, setAuthed}) {
 const [screen,setScreen]=useState('login'); const [notice,setNotice]=useState('');
 const submit=(e,next='dashboard')=>{e.preventDefault(); setNotice(''); if(screen==='forgot'){setNotice('If an account exists, reset instructions have been sent.');return} if(screen==='signup'){setScreen('verify');return} if(screen==='reset'){setNotice('Your password was reset. You can now log in.'); setScreen('login');return} setAuthed(true);setMode(next)};
 const title={login:['Welcome back','Sign in to continue managing your restaurants.'],signup:['Create your owner account','Start with a secure foundation for your restaurant group.'],forgot:['Reset your password','We’ll send a secure link to your registered email.'],reset:['Choose a new password','Use at least 8 characters, including a letter and a number.'],verify:['Check your inbox','We sent a verification link to your email address.']}[screen];
 return <main className="auth"><section className="auth-aside"><div className="brand"><Mark/><b>RestroVico</b></div><div className="aside-copy"><p className="eyebrow">MULTI-OUTLET RESTAURANT CONTROL</p><h1>Your restaurant group,<br/>ready to grow.</h1><p>Set up locations, keep ownership clear, and build operations on a dependable base.</p></div><div className="aside-note"><Icon name="check"/> Built for owners. Designed for what comes next.</div></section><section className="auth-panel"><div className="auth-card"><div className="mobile-brand"><Mark/><b>RestroVico</b></div><p className="eyebrow">OWNER WORKSPACE</p><h2>{title[0]}</h2><p className="muted">{title[1]}</p>{notice&&<div className="notice">{notice}</div>}
 {screen==='verify'?<><div className="verify-icon"><Icon name="check"/></div><p className="muted">Open the email, select <b>Verify email</b>, then return here to continue.</p><Button onClick={()=>{setAuthed(true);setMode('onboarding')}}>I’ve verified my email <Icon name="arrow"/></Button><button className="text-button" onClick={()=>setNotice('A new verification email has been sent.')}>Resend verification email</button></>:
 <form onSubmit={submit}>{screen==='signup'&&<><Field label="Full name"><input required minLength="2" placeholder="e.g. Aditi Mehra"/></Field><Field label="Mobile number"><input required type="tel" placeholder="+91 98765 43210"/></Field></>}<Field label={screen==='forgot'?'Email address':'Email or mobile'}><input required type={screen==='forgot'?'email':'text'} placeholder={screen==='forgot'?'you@example.com':'you@example.com or +91…'}/></Field>{screen!=='forgot'&&<><Field label={screen==='reset'?'New password':'Password'}><input required type="password" minLength="8" placeholder="••••••••"/></Field>{(screen==='signup'||screen==='reset')&&<Field label="Confirm password"><input required type="password" minLength="8" placeholder="••••••••"/></Field>}</>}{screen==='signup'&&<label className="check"><input required type="checkbox"/> I accept the Terms of Service and Privacy Policy.</label>}{screen==='login'&&<div className="form-row"><label className="check"><input type="checkbox"/> Remember me</label><button type="button" className="text-button" onClick={()=>setScreen('forgot')}>Forgot password?</button></div>}<Button type="submit">{screen==='login'?'Sign in':screen==='signup'?'Create owner account':screen==='forgot'?'Send reset link':'Reset password'} <Icon name="arrow"/></Button></form>}
 {screen==='login'&&<p className="switch">New to RestroVico? <button onClick={()=>setScreen('signup')}>Create owner account</button></p>}{screen!=='login'&&screen!=='verify'&&<p className="switch">Already have an account? <button onClick={()=>setScreen('login')}>Sign in</button></p>}</div></section></main>
}

function RestaurantForm({restaurant,onSave,onCancel}) { const [form,setForm]=useState(restaurant||{name:'',type:'Restaurant',mobile:'',address:'',city:'',state:'',pin:''}); const upd=e=>setForm({...form,[e.target.name]:e.target.value}); const submit=e=>{e.preventDefault();onSave(form)}; return <div className="page form-page"><div className="page-top"><div><p className="eyebrow">RESTAURANTS</p><h1>{restaurant?'Edit restaurant':'Add a restaurant'}</h1><p className="muted">{restaurant?'Keep this location’s details accurate.':'Add the minimum details to get this location ready.'}</p></div><Button kind="ghost" onClick={onCancel}>Cancel</Button></div><form className="card form-card" onSubmit={submit}><div className="form-grid"><Field label="Restaurant / outlet name"><input required name="name" value={form.name} onChange={upd} placeholder="e.g. Spice Garden - Noida"/></Field><Field label="Business type"><select name="type" value={form.type} onChange={upd}><option>Restaurant</option><option>Cafe</option><option>QSR</option><option>Cloud Kitchen</option><option>Food Court</option><option>Other</option></select></Field><Field label="Restaurant mobile"><input required name="mobile" value={form.mobile} onChange={upd} type="tel" placeholder="+91 98765 43210"/></Field><Field label="Restaurant email (optional)"><input type="email" placeholder="ops@example.com"/></Field><Field label="Address"><input required name="address" value={form.address} onChange={upd} placeholder="Building, street, locality"/></Field><Field label="City"><input required name="city" value={form.city} onChange={upd} placeholder="City"/></Field><Field label="State"><input required name="state" value={form.state} onChange={upd} placeholder="State"/></Field><Field label="PIN code"><input required name="pin" value={form.pin} onChange={upd} inputMode="numeric" pattern="[0-9]{6}" placeholder="6-digit PIN"/></Field></div><div className="form-actions"><Button kind="ghost" onClick={onCancel}>Cancel</Button><Button type="submit">Save restaurant <Icon name="arrow"/></Button></div></form></div> }

function App(){ const [authed,setAuthed]=useState(false),[mode,setMode]=useState('dashboard'),[restaurants,setRestaurants]=useState(initialRestaurants),[editing,setEditing]=useState(null),[toast,setToast]=useState(''); const active=restaurants.filter(r=>r.status==='Active').length; const save=r=>{if(editing){setRestaurants(restaurants.map(x=>x.id===editing.id?{...x,...r}:x));setToast('Restaurant updated successfully.')}else{setRestaurants([...restaurants,{...r,id:Date.now(),status:'Active',code:`RV-R${String(restaurants.length+1).padStart(4,'0')}`}]);setToast('Restaurant added successfully.')}setEditing(null);setMode('restaurants')}; if(!authed)return <Auth setMode={setMode} setAuthed={setAuthed}/>; if(mode==='onboarding')return <main className="onboarding"><div className="brand"><Mark/><b>RestroVico</b></div><section><p className="eyebrow">STEP 1 OF 1</p><h1>Let’s add your first restaurant.</h1><p className="muted">This gives your workspace a home. You can add more locations any time.</p><div className="onboard-actions"><Button onClick={()=>setMode('new')}>Add first restaurant <Icon name="arrow"/></Button><Button kind="ghost" onClick={()=>setMode('dashboard')}>I’ll do this later</Button></div></section><div className="onboard-progress"><span></span><b>Restaurant setup</b><small>Owner account complete</small></div></main>;
 if(mode==='new'||editing)return <Shell mode={mode} setMode={setMode} setAuthed={setAuthed}><RestaurantForm restaurant={editing} onSave={save} onCancel={()=>{setEditing(null);setMode('restaurants')}}/></Shell>;
 return <Shell mode={mode} setMode={setMode} setAuthed={setAuthed}><main className="page">{toast&&<div className="toast">✓ {toast}<button onClick={()=>setToast('')}>×</button></div>}{mode==='dashboard'?<><div className="page-top"><div><p className="eyebrow">OWNER OVERVIEW</p><h1>Good morning, Aditi.</h1><p className="muted">Here’s your restaurant group at a glance.</p></div><Button onClick={()=>setMode('new')}><Icon name="plus"/> Add restaurant</Button></div><div className="stats"><article><span>Total restaurants</span><strong>{restaurants.length}</strong><small>Across your restaurant group</small></article><article><span>Active locations</span><strong>{active}</strong><small>Ready for future operations</small></article><article><span>Workspace status</span><strong className="ready">Ready</strong><small>Owner account verified</small></article></div><section className="section-head"><div><h2>Your restaurants</h2><p className="muted">Manage your locations and their setup details.</p></div><button className="link" onClick={()=>setMode('restaurants')}>View all <Icon name="arrow"/></button></section><RestaurantCards restaurants={restaurants.slice(0,3)} edit={r=>setEditing(r)}/></>:mode==='restaurants'?<><div className="page-top"><div><p className="eyebrow">RESTAURANTS</p><h1>All locations</h1><p className="muted">{restaurants.length} locations in your restaurant group.</p></div><Button onClick={()=>setMode('new')}><Icon name="plus"/> Add restaurant</Button></div><div className="toolbar"><input aria-label="Search restaurants" placeholder="Search by name or city"/><select aria-label="Filter restaurant status"><option>All statuses</option><option>Active</option><option>Inactive</option><option>Archived</option></select></div><RestaurantCards restaurants={restaurants} edit={r=>setEditing(r)}/></>:<Profile/>}</main></Shell> }
function RestaurantCards({restaurants,edit}){return <div className="restaurants">{restaurants.map(r=><article className="restaurant" key={r.id}><div className="restaurant-symbol">{r.name.slice(0,1)}</div><div className="restaurant-info"><div><h3>{r.name}</h3><span>{r.type} · {r.city}</span></div><p><b>{r.code}</b><i className={r.status.toLowerCase()}></i>{r.status}</p></div><button className="edit" onClick={()=>edit(r)}>Edit <Icon name="arrow"/></button></article>)}</div>}
function Profile(){return <><div className="page-top"><div><p className="eyebrow">PROFILE & SETTINGS</p><h1>Your owner account</h1><p className="muted">Manage the details connected to your workspace.</p></div></div><section className="profile card"><div className="avatar">AM</div><div><h2>Aditi Mehra</h2><p className="muted">Owner · Verified account</p></div><Button kind="ghost">Edit profile</Button></section><section className="settings card"><div><h3>Sign-in & security</h3><p>Update your password to keep your account protected.</p></div><Button kind="ghost">Change password</Button></section></>}
function Shell({children,mode,setMode,setAuthed}){const nav=[['dashboard','Dashboard','grid'],['restaurants','Restaurants','store'],['profile','Profile & settings','user']];return <div className="app-shell"><aside className="sidebar"><div className="brand"><Mark/><b>RestroVico</b></div><nav>{nav.map(([id,label,icon])=><button key={id} className={mode===id?'active':''} onClick={()=>setMode(id)}><Icon name={icon}/>{label}</button>)}</nav><div className="sidebar-bottom"><div className="owner"><div className="avatar">AM</div><span><b>Aditi Mehra</b><small>Owner</small></span></div><button className="logout" onClick={()=>setAuthed(false)}><Icon name="logout"/> Log out</button></div></aside><div className="content">{children}</div><nav className="bottom-nav">{nav.map(([id,label,icon])=><button key={id} className={mode===id?'active':''} onClick={()=>setMode(id)}><Icon name={icon}/><span>{label.split(' ')[0]}</span></button>)}</nav></div>}
createRoot(document.getElementById('root')).render(<App/>);
